server:
  port: ${PORT}
spring:
  profiles:
    default: ${SPRING_PROFILE}
  application:
    name: payment-service
    port: ${PORT}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER}
          jwk-set-uri: ${AUTH_JWKS}
  kafka:
    bootstrap-servers: http://${KAFKA_HOST}:9092
    trusted-packages: com.innowise.external.dto.kafka

feign:
  payment:
    provider:
      url: http://www.randomnumberapi.com/api/v1.0
      payment-endpoint: /random?min=0&max=10&count=1
      name: external-payment-provider

kafka:
  topic:
    payment-result-topic: payment.result.msg
    order-created-topic: order.created.msg

springdoc:
  swagger-ui:
    csrf:
      enabled: true
swagger-server: http://gateway-service/api/v1/payments-swagger/

mongo:
  client-uri: mongodb://admin:admin@${MONGO_HOST}:27017/payment_service?authSource=admin
  username: admin
  password: admin
  connection-uri: mongodb://${MONGO_HOST}:27017/payment_service?authSource=admin

liquibase:
  enabled: true
  change-log: db/changelog-master.yaml

otel:
  traces:
    sampler: always_on
  exporter:
    otlp:
      traces:
        endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
        protocol: grpc
      metrics:
        endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
        protocol: grpc
      logs:
        endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
        protocol: grpc